// <auto-generated />
using System;
using EventTimings.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventTimings.Api.Data.Migrations
{
    [DbContext(typeof(EventTimingsDbContext))]
    [Migration("20260523133354_PersistTimingSessions")]
    partial class PersistTimingSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("EventTimings.Api.Data.OfficialEntity", b =>
                {
                    b.Property<string>("OfficialId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PinSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("OfficialId");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.ToTable("Officials");
                });

            modelBuilder.Entity("EventTimings.Api.Data.RiderEntity", b =>
                {
                    b.Property<string>("RiderId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BibNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RiderId");

                    b.HasIndex("BibNumber")
                        .IsUnique();

                    b.HasIndex("RouteTypeId");

                    b.ToTable("Riders");
                });

            modelBuilder.Entity("EventTimings.Api.Data.RouteTypeEntity", b =>
                {
                    b.Property<string>("RouteTypeId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("DistanceMiles")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("RouteTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RouteTypes");
                });

            modelBuilder.Entity("EventTimings.Api.Data.TimingSessionEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiderName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("RiderId", "StoppedAt");

                    b.ToTable("TimingSessions");
                });

            modelBuilder.Entity("EventTimings.Api.Data.RiderEntity", b =>
                {
                    b.HasOne("EventTimings.Api.Data.RouteTypeEntity", "RouteType")
                        .WithMany("Riders")
                        .HasForeignKey("RouteTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RouteType");
                });

            modelBuilder.Entity("EventTimings.Api.Data.TimingSessionEntity", b =>
                {
                    b.HasOne("EventTimings.Api.Data.RiderEntity", "Rider")
                        .WithMany()
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("EventTimings.Api.Data.RouteTypeEntity", b =>
                {
                    b.Navigation("Riders");
                });
#pragma warning restore 612, 618
        }
    }
}
