// <auto-generated />
using System;
using EventTimings.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventTimings.Api.Data.Migrations
{
    [DbContext(typeof(EventTimingsDbContext))]
    [Migration("20260518160515_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventTimings.Api.Data.OfficialEntity", b =>
                {
                    b.Property<string>("OfficialId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PinSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("OfficialId");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.ToTable("Officials");
                });

            modelBuilder.Entity("EventTimings.Api.Data.RiderEntity", b =>
                {
                    b.Property<string>("RiderId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("BibNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RouteTypeId")
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("RiderId");

                    b.HasIndex("BibNumber")
                        .IsUnique();

                    b.HasIndex("RouteTypeId");

                    b.ToTable("Riders");
                });

            modelBuilder.Entity("EventTimings.Api.Data.RouteTypeEntity", b =>
                {
                    b.Property<string>("RouteTypeId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("DistanceMiles")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("RouteTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RouteTypes");
                });

            modelBuilder.Entity("EventTimings.Api.Data.RiderEntity", b =>
                {
                    b.HasOne("EventTimings.Api.Data.RouteTypeEntity", "RouteType")
                        .WithMany("Riders")
                        .HasForeignKey("RouteTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RouteType");
                });

            modelBuilder.Entity("EventTimings.Api.Data.RouteTypeEntity", b =>
                {
                    b.Navigation("Riders");
                });
#pragma warning restore 612, 618
        }
    }
}
